#! /bin/sh

xrdb ~/.Xresources
#sxhkd 

if test "$(hostname)" = "a-smol-workstation"; then
    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9
    xrdb ~/.XResources
    polybar -r top&
    #bspc monitor HDMI-2 -d iota gamma mu delta lambda kappa
elif test "$(hostname)" = "a-workstation"; then
    #${HOME}/bin/setup-screens
    #synergys -c ${HOME}/.synergy.conf
    #feh --bg-center /home/dbe/Dropbox/bgs/light/173.jpg /home/dbe/Dropbox/bgs/light/94.jpg /home/dbe/Dropbox/bgs/light/Lake\ Tahoe\ Colors.jpg
     xrandr --output DVI-D-0 --mode 1920x1080 --pos 2520x690 --rotate normal --output DP-4 --mode 2560x1440 --pos 0x0 --rotate left --output DP-4 --off --output HDMI-0 --primary --mode 1920x1080 --pos 1440x320 --rotate left --output DP-4 --off
     bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
     bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
     bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9
     #xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output DVI-D-1 --mode 1920x1080 --rotate normal --right-of HDMI-1
     polybar -r top &
     polybar -r work1 &
     polybar -r off &
fi
urxvt &
bspc config border_width         0
bspc config window_gap          37

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b

# set left_ptr in x root (wallpaper)
#xsetroot -cursor_name left_ptr
xsetroot -xcf /usr/share/icons/whiteglass/cursors/left_ptr 16
