#! /bin/sh

xrdb ~/.Xresources
#sxhkd 

if test "$(hostname)" = "home-station"; then
    bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
    xrdb ~/.XResources
    polybar -r top&
fi

bspc config border_width         0
bspc config window_gap           15 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config presel_feedback_color \#aaaaaa

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom -b
alacritty &

# set left_ptr in x root (wallpaper)
# xsetroot -cursor_name left_ptr
# xsetroot -xcf /usr/share/icons/whiteglass/cursors/left_ptr 16
